[package]
name    = "cancer"
version = "0.1.0"

authors = ["meh. <meh@schizofreni.co>"]
license = "GPL-3"
build   = "build.rs"

description = "Terminal cancer."
repository  = "https://github.com/meh/terme"
keywords    = ["term", "pty"]

[profile.release]
lto   = true
panic = "abort"

[build-dependencies]
pkg-config = "0.3"

[dependencies]
log        = "0.3"
env_logger = "0.3"

libc          = "0.2"
bitflags      = "0.7"
bit-vec       = "0.4"
fnv           = "1.0"
lru-cache     = "0.1"
shlex         = "0.1"
schedule_recv = "0.1"
itertools     = "0.5"
control-code  = "0.4.7"

clap     = "2"
app_dirs = "1.1"
toml     = "0.1"
palette  = "0.2"
regex    = "0.1"

unicode-segmentation = "0.1"
unicode-width        = "0.1"

[target.'cfg(any(target_os = "linux", target_os = "freebsd", target_os = "netbsd", target_os = "openbsd", target_os = "dragonfly"))'.dependencies]
xcb       = { version = "0.7.6", features = ["thread"], optional = true }
xcb-util  = { version = "0.1.5", features = ["icccm", "ewmh", "thread"], optional = true }
xkbcommon = { version = "0.2",   features = ["x11", "compose"], git = "https://github.com/meh/xkbcommon-rs", optional = true }

wayland-client = { version = "0.7", optional = true }
wayland-kbd    = { version = "0.6", optional = true }
wayland-window = { version = "0.4", optional = true }
egl            = { version = "0.2", optional = true }
gl             = { version = "0.6", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
objc            = "0.2"
cocoa           = "0.5.0"
core-foundation = "0"
core-graphics   = "0.4"

[features]
default = ["x11"]
static  = []
fuzzy   = ["afl", "afl-plugin"]

wayland = ["wayland-client", "wayland-kbd", "wayland-window", "egl", "gl"]
x11     = ["xcb", "xcb-util", "xkbcommon"]

[dependencies.afl]
version  = "0.1"
optional = true

[dependencies.afl-plugin]
version  = "0.1"
optional = true
