[package]
name    = "cancer"
version = "0.1.0"

authors = ["meh. <meh@schizofreni.co>"]
license = "WTFPL"

description = "Terminal cancer."
repository  = "https://github.com/meh/terme"
keywords    = ["term", "pty"]

[profile.release]
debug = true
lto   = true
panic = "abort"

[dependencies]
log        = "0.3"
env_logger = "0.3"

libc          = "0.2"
bitflags      = "0.7"
bit-vec       = "0.4"
fnv           = "1.0"
lru-cache     = "0.1"
shlex         = "0.1"
schedule_recv = "0.1"
itertools     = "0.5"
control-code  = "0.4"

clap     = "2"
app_dirs = "1.1"
toml     = "0.1"
picto    = "0.4"

unicode-segmentation = "0.1"
unicode-width        = "0.1"

[target.'cfg(target_os = "linux")'.dependencies]
xcb       = { version = "0.7.5", features = ["thread"] }
xcb-util  = { version = "0.1.5", features = ["icccm", "ewmh", "thread"] }
xkbcommon = { version = "0.2",   features = ["x11"] }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.5"
