[environment]
display = ":0.0"
program = "zsh"

[style]
font  = "monospace 11px"
blink = 800

margin  = 0
spacing = 0

[style.color]
foreground = "#c6c6c6"
background = "#000000"
underline  = "#060"
strike     = "#f00"

[style.cursor]
shape = "beam"
blink = true

foreground = "#fff"
background = "#b21818"

[color]
0  = "#000000"
1  = "#b21818"
2  = "#18b218"
3  = "#BE5F00"
4  = "#6D85BA"
5  = "#b218b2"
6  = "#18b2b2"
7  = "#b2b2b2"
8  = "#686868"
9  = "#FF5454"
10 = "#54FF54"
11 = "#FFFF54"
12 = "#73A5FF"
13 = "#FF54FF"
14 = "#54FFFF"
15 = "#ffffff"
