[environment]
display = ":0.0"
program = "zsh"
term    = "cancer-256color"

bell   = 100
cache  = 2048
scroll = 2048
batch  = 30

[input]
prefix = "L-a"

[style]
font  = "monospace 11px"
blink = 500
bold  = "bright"

margin  = 2
spacing = 0

[style.color]
foreground    = "#c6c6c6"
background    = "#000000"
underline     = false
strikethrough = false

[style.cursor]
shape = "block"
blink = false

foreground = "#fff"
background = "#b21818"

[style.status]
background = "#b21818"
foreground = "#fff"
attributes = "bold"

[color]
0  = "#000000"
1  = "#B21818"
2  = "#18B218"
3  = "#BE5F00"
4  = "#6D85BA"
5  = "#B218B2"
6  = "#18B2B2"
7  = "#B2B2B2"
8  = "#686868"
9  = "#FF5454"
10 = "#54FF54"
11 = "#FFFF54"
12 = "#73A5FF"
13 = "#FF54FF"
14 = "#54FFFF"
15 = "#FFFFFF"
