[environment]
display = ":0.0"
program = "zsh"
term    = "cancer-256color"
bell    = 100

batch  = 33
cache  = 2048
scroll = 2048

[input]
prefix = "L-a"
locale = "en_GB.UTF-8"

[style]
font      = "monospace 11px"
ligatures = false

blink = 500
bold  = "bright"

margin  = 2
spacing = 0

[style.color]
foreground    = "#c6c6c6"
background    = "#000000"
underline     = false
strikethrough = false

[style.cursor]
shape = "block"
blink = false

foreground = "#fff"
background = "#b21818"

[overlay]
status = false

[overlay.hinter]
matcher = '(gopher|https?|ftp)://(-\.)?([^\s/?\.#]+\.?)+(/[^\s]*)?'
opener  = "firefox"

[overlay.hinter.style]
foreground = "#ffffff"
background = "#b21818"
attributes = "bold"

[overlay.hinter.1]
label   = "1234567890"
matcher = '(gopher|https?|ftp)://(-\.)?([^\s/?\.#]+\.?)+(/[^\s]*)\.(jpg|jpeg|webm|gif|png|mp4|avi)'
opener  = "mpv"

[overlay.hinter.1.style]
foreground = "#18b218"
background = "#ffffff"
attributes = "bold"

[color]
0  = "#000000"
1  = "#B21818"
2  = "#18B218"
3  = "#BE5F00"
4  = "#6D85BA"
5  = "#B218B2"
6  = "#18B2B2"
7  = "#B2B2B2"
8  = "#686868"
9  = "#FF5454"
10 = "#54FF54"
11 = "#FFFF54"
12 = "#73A5FF"
13 = "#FF54FF"
14 = "#54FFFF"
15 = "#FFFFFF"
